#ifndef IO_H
#define IO_H

#define LAUNCHPAD

typdef enum 
{
#if defined(LAUNCHPAD) 
    IO_TEST_LED = IO_10,
    IO_UART_RXD = IO_11,
    IO_UART_TXD = IO_12,
    IO_LINE_DETECT_FRONT_LEFT = IO_13,
    IO_UNUSED_2 = IO_14,
    IO_UNUSED_3 = IO_15,
    IO_I2C_SCL = IO_16,
    IO_I2C_SDA = IO_17,
    IO_IR_REMOTE = IO_20,
    IO_MOTORS_LEFT_CC_1 = IO_21,
    IO_MOTORS_LEFT_CC_2 = IO_22,
    IO_RANGE_SENSOR_FRONT_INT = IO_23,
    IO_XSHUT_FRONT = IO_24,
    IO_UNUSED_11 = IO_25,
    IO_PWM_MOTORS_LEFT = IO_26,
    IO_UNUSED_13 = IO_27,
#elif defined(NSUMO)
    IO_LINE_DETECT_FRONT_RIGHT = IO_10,
    IO_UART_RXD = IO_11,
    IO_UART_TXD = IO_12,
    IO_LINE_DETECT_FRONT_LEFT = IO_13,
    IO_LINE_DETECT_BACK_LEFT = IO_14,
    IO_LINE_DETECT_BACK_RIGHT = IO_15,
    IO_I2C_SCL = IO_16,
    IO_I2C_SDA = IO_17,
    IO_IR_REMOTE = IO_20,
    IO_RANGE_SENSOR_FRONT_INT = IO_21,
    IO_XSHUT_FRONT = IO_22,
    IO_UNUSED_1 = IO_23,
    IO_MOTORS_LEFT_CC_2 = IO_24,
    IO_MOTORS_LEFT_CC_1 = IO_25,
    IO_TEST_LED = IO_26,
    IO_MOTORS_RIGHT_CC_2 = IO_27,
    IO_XSHUT_FRONT_RIGHT = IO_30,
    IO_XSHUT_RIGHT = IO_31,
    IO_XSHUT_FRONT_LEFT = IO_32,
    IO_XSHUT_LEFT = IO_33,
    IO_UNUSED_2 = IO_34,
    IO_PWM_MOTORS_LEFT = IO_35,
    IO_PWM_MOTORS_RIGHT = IO_36,
    IO_MOTORS_RIGHT_CC_1 = IO_37,
  #endif
} io_e;

#endif 
