name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: terencemat/msp430-gcc-9.3.1.11:latest  # Docker image from Docker Hub
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build with Make
        run: make
